import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import Header from 'components/header/header';
import styles from 'styles/ticket.module.scss';
import subscribe from 'json/subscribe.json';

const Ticket: NextPage = () => {
	const [option, setOption] = useState(3);
	const [duration, setDuration] = useState('1 месяц');
	const [price, setPrice] = useState(249);
	const [fullPrice, setFullPrice] = useState(249);
	const [percent, setPercent] = useState('0%');

	return (
		<div className="container">
			<Head>
				<title>Подписка</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className="main">
				<div className={styles.masthead}>
					<h1>Получите полный доступ ко всем нашим фильмам.</h1>
				</div>

				<div className={styles.widget}>
					<div className={styles.subscription}>
						<div className={styles.subscription__title}>
							<h1>View +</h1>
							<span>Премиальная подписка на наш сервис</span>
							{subscribe.map((subscribe, id) => {
								return (
									<div
										key={id}
										className={
											option === id
												? styles.product__option__active
												: styles.product__option
										}
										onClick={() => {
											setDuration(subscribe.duration);
											setPrice(subscribe.price);
											setFullPrice(subscribe.full_price);
											setPercent(subscribe.percent);
											setOption(id);
										}}
									>
										<p>Подписка на {subscribe.duration}</p>
										<div className={styles.price}>
											<span>₽</span>
											<h2>{subscribe.monthly} / мес.</h2>
										</div>
										<p>Экономия {subscribe.economy} ₽ / г.</p>
									</div>
								);
							})}
							<div className={styles.price__wrap}>
								<div className={styles.price}>
									<div className={styles.price}>
										<h2>{price} RUB</h2>
										{fullPrice != 249 ? <p>{fullPrice} RUB</p> : null}
									</div>
									{percent != '0%' ? (
										<div className={styles.percent}>
											<p>{percent}</p>
										</div>
									) : null}
								</div>
								<p>
									Cписание средств раз в {duration}. Вы можете в любой момент
									отменить подписку на сайте.
								</p>
							</div>
							<Link href="/">Оформить подписку</Link>
						</div>
					</div>
				</div>

				<div className={styles.privileges__list}>
					<h1>Новые возможности</h1>
					<div className={styles.item}>
						<Image
							src="/svg/check/check.svg"
							width={14}
							height={14}
							alt="svg"
						/>
						<p>Все возможности стандартной подписки</p>
					</div>

					<div className={styles.item}>
						<Image
							src="/svg/check/active_check.svg"
							width={14}
							height={14}
							alt="svg"
						/>
						<p>Полный доступ ко всем фильмам сервиса</p>
					</div>
					<div className={styles.item}>
						<Image
							src="/svg/check/active_check.svg"
							width={14}
							height={14}
							alt="svg"
						/>
						<p>Особая галочка для вашего профиля</p>
					</div>

					<div className={styles.item}>
						<span>*</span>
						<p>
							Автоматическое списание средств. <br />
							Вы можете в любой момент отменить подписку на сайте.
						</p>
					</div>
				</div>
				<div className={styles.faq}>
					<h1>Часто задаваемые вопросы</h1>
					<div className={styles.items}>
						<div className={styles.item}>Какой план мне подходит?</div>
						<div className={styles.item}>
							Каковы ограничения для каждого плана?
						</div>
						<div className={styles.item}>
							Как Vercel рассчитывает использование?
						</div>
					</div>
				</div>
			</main>
		</div>
	);
};

export default Ticket;
