import { useState } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import Header from 'components/header/header';
import Footer from 'components/footer/footer';

import styles from './user.module.scss';

const User: NextPage = () => {
    return (
		<div className="container">
			<Head>
				<title>Подписка</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className="main">
                <div className={styles.profile__title}>
                    <h2>Username</h2>
                    <p>Базовый</p>
                </div>
                <div className={styles.profile__tabs}>
                    <button>
                        Профиль
                    </button>
                    <button>
                        Друзья
                    </button>
                    <button>
                        Группы
                    </button>
                    <button>
                        Подписка
                    </button>
                </div>
            </main>
        </div>
    );
}

export default User;