import { useRouter } from 'next/router';
import { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/movie.module.scss';

import Header from 'components/header/header';
import Footer from 'components/footer/footer';

import movies from 'json/movies.json';

const VideoPlayer = () => {
	const router = useRouter();
	const { movie } = router.query;
	
	return (
		<div className={styles.video}>
			{movies
				.filter((movies) => movies.ref === movie)
				.map((movie, id) => {
					return (
						<video
							key={id}
							src={movie.video}
							loop
							controls
							playsInline
						/>
					);
				})
			}
		</div>
	);
};

const Movie: NextPage = () => {
 	const router = useRouter();
	const { movie } = router.query;

	return (
		<div className="container">
			<Head>
				<title>
					{movies
						.filter((movies) => movies.ref === movie)
						.map((movie) => {
							return movie.name;
						})}
				</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className="main">
				{movies
					.filter((movies) => movies.ref === movie)
					.map((movie, id) => {
						return (
							<div className={styles.movie} key={id}>
								<div className={styles.movie__rightside}>
									<Image
										src={movie.image}
										width={300}
										height={450}
										className={styles.image}
										draggable="false"
										alt="image"
									/>
								</div>

								<div className={styles.movie__content}>
									<div className={styles.movie__masthead__content}>
										<div className={styles.first__part}>
											<h1>
												{movie.name} ({movie.release})
											</h1>
											<span>
												{movie.euName}{' '}
												<span className={styles.age}>{movie.age}+</span>
											</span>
										</div>

										<div className={styles.second__part}>
											<h2>О фильме</h2>
											<div className={styles.about__movie}>
												<span>Год производства</span>
												<span>{movie.release}</span>
											</div>
											<div className={styles.about__movie}>
												<span>Страна</span>
												<span>{movie.country}</span>
											</div>
											<div className={styles.about__movie}>
												<span>Жанр</span>
												<span>{movie.genre}</span>
											</div>
											<div className={styles.about__movie}>
												<span>Возраст</span>
												<span>{movie.age}+</span>
											</div>
											<div className={styles.about__movie}>
												<span>Длительность</span>
												<span>{movie.duration}</span>
											</div>
										</div>
									</div>
									<VideoPlayer />
								</div>
							</div>
						);
					})}
			</main>

			<Footer />
		</div>
	);
};

export default Movie;
