import { useRouter } from 'next/router';
import Head from 'next/head';

import Header from 'components/header/header';
import Footer from 'components/footer/footer';

import movies from 'pages/api/json/movies.json';

import styles from 'pages/movies/movie.module.scss';

const Movie = () => {
	return (
		<div className="container">
			<Head>
				<title>
					{movies
						.filter(
							(movies) => movies.original_title.replace(/\s/g, '') === movie
						)
						.map((movie) => {
							return movie.original_title;
						})}
				</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className="main">
				{movies
					.filter(
						(movies) => movies.original_title.replace(/\s/g, '') === movie
					)
					.map((movie, id) => {
						return (
							<div className={styles.movie} key={movie.original_title}>
								<div className={styles.movie__content}>
									<div className={styles.movie__wrap}>
										<div className={styles.movie__content__image}>
											<img
												src={`https://image.tmdb.org/t/p/w500${movie.poster_path}`}
												width={300}
												height={450}
												alt="image"
												draggable="false"
											/>
										</div>
										<div className={styles.movie__masthead__content}>
											<div className={styles.first__part}>
												<h1>
													{movie.title} ({movie.release_date})
												</h1>
												<span>
													{movie.original_title}{' '}
													<span className={styles.age}>{movie.age}+</span>
												</span>
											</div>

											<div className={styles.second__part}>
												<h2>О фильме</h2>
												<div className={styles.about__movie}>
													<span>Год производства</span>
													<span>{movie.release_date}</span>
												</div>
												<div className={styles.about__movie}>
													<span>Страна</span>
													<span>{movie.country}</span>
												</div>
												<div className={styles.about__movie}>
													<span>Жанр</span>
													<span>{movie.genre}</span>
												</div>
												<div className={styles.about__movie}>
													<span>Возраст</span>
													<span>{movie.age}+</span>
												</div>
												<div className={styles.about__movie}>
													<span>Длительность</span>
													<span>{movie.duration}</span>
												</div>
											</div>
											<div className={styles.video}>
												<video src={movie.trailer} loop controls playsInline />
											</div>
										</div>
									</div>
								</div>
							</div>
						);
					})}
			</main>
			<Footer />
		</div>
	);
};

export default Movie;
