import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from 'styles/movies.module.scss';

import Header from 'components/header/header';
import Footer from 'components/footer/footer';

import movies from 'json/movies.json';

const Movies: NextPage = () => {
	const [isActiveFlag, setIsActiveFlag] = useState(false);

	return (
		<div className="container">
			<Head>
				<title>Фильмы</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className={styles.main}>
				<div className={styles.page__wrap}>
					<div className={styles.search__header}>
						<h1>Каталог</h1>
						<button>По рейтингу</button>
					</div>
					<input type="text" placeholder="Поиск по названию..." />
					<div className={styles.cards__wrap}>
						{movies.map((movie, id) => {
							return (
								<div className={styles.card} key={id}>
									<Link href={`/movies/${movie.ref}`} draggable="false">
										<Image
											src={movie.image}
											width={210}
											height={270}
											alt="image"
											draggable="false"
										/>
										<div className={styles.card__score}>{movie.score}</div>
									</Link>
								</div>
							);
						})}
					</div>
				</div>
				<div className={styles.sort__wrap}>
					<h1>1</h1>
				</div>
			</main>

			<Footer />
		</div>
	);
};

export default Movies;
