import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import Header from 'components/header/header';
import Footer from 'components/footer/footer';
import Demo from 'components/ui/demo/demo';
import styles from './index.module.scss';

const Home: NextPage = () => {
	return (
		<div className="container">
			<Head>
				<title>Главная</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main className="main">
				<div className={styles.masthead}>
					<h1>
						Один сервис <br />
						Море фильмов
					</h1>
					<p>
						Наша работа приукрасить ваш вечер предоставив лучшие фильмы нашего
						сервиса. Регистрируйтесь, общайтесь, предлагайте фильмы друзьям и
						смотрите их вместе.
					</p>
					<div className={styles.buttons}>
						<Link href="/movies">Начните просмотр</Link>
						<Link href="/signup">Зарегистрируйтесь</Link>
					</div>
				</div>

				<div className={styles.cards}>
					<Link href="/movies" className={styles.primary__card}>
						<Image
							src="/images/logo2.png"
							width={100}
							height={100}
							alt="logo"
							draggable={false}
						/>
						<h1>Небо</h1>
						<span>Автор: Attato</span>
						<p>
							Привнесение ярких эмоций <br /> в вашу жизнь.
						</p>
						<button>
							Начало просмотра{' '}
							<Image
								src="/svg/home/link.svg"
								width={16}
								height={16}
								alt="svg"
								draggable={false}
							/>
						</button>
					</Link>
					<div className={styles.secondary__cards}>
						<Link href="/subscribe?product=3" className={styles.card}>
							<h1>Небо +</h1>
							<p>
								Выделитесь из толпы и получите уйму возможностей с помощью
								<br /> подписки.
							</p>
						</Link>
						<Link href="/user?tab=Профиль" className={styles.card}>
							<h1>Вместе</h1>
							<p>
								Общайтесь с друзьями прямо во время просмотра любимых фильмов.
							</p>
						</Link>
					</div>
				</div>
			</main>
			<Footer />
		</div>
	);
};

export default Home;
