import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import Header from 'components/header/header';
import Footer from 'components/footer/footer';
import Demo from 'components/ui/demo/demo';
import styles from './index.module.scss';

const Home: NextPage = () => {
	return (
		<div className="container">
			<Head>
				<title>Главная</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className="main">
				<div className={styles.masthead}>
					<div className={styles.row__wrap}>
						<div className={styles.masthead__content}>
							<h1>
								Один сервис. <br />
								Море фильмов.
							</h1>
							<p>
								View - это все, что вам нужно, чтобы провести свой день именно
								так, как вы себе представляете.
							</p>
							<div className={styles.masthead__button__wrap}>
								<Link href="/movies">Смотреть бесплатно</Link>
								<Link href="/subscription">Подписаться</Link>
							</div>
						</div>

						<Demo url="view">
							<div className={styles.demo_content}></div>
						</Demo>
					</div>
				</div>
			</main>
			<Footer />
		</div>
	);
};

export default Home;
