import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import Header from 'components/header/header';
import Footer from 'components/footer/footer';

import styles from './index.module.scss';

const Home: NextPage = () => {
	return (
		<div className="container">
			<Head>
				<title>Главная</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className="main">
				<div className={styles.masthead}>
					<div className={styles.row__wrap}>
						<div className={styles.masthead__content}>
							<h1>
								Один сервис. <br />
								Море фильмов.
							</h1>
							<p>
								View - это все, что вам нужно, чтобы провести свой день именно
								так, как вы себе представляете.
							</p>
							<div className={styles.masthead__button__wrap}>
								<Link href="/movies">Смотреть бесплатно</Link>
								<Link href="/subscription">Подписаться</Link>
							</div>
						</div>

						<div className={styles.demonstration__blocks}>
							<div className={styles.demonstration__block}>
								<div className={styles.header}>
									<div className={styles.window__traffic}>
										<span className={styles.close}></span>
										<span className={styles.minimize}></span>
										<span className={styles.fullscreen}></span>
									</div>
									<div className={styles.browser__input}>
										<p>view</p>

										<Image
											src="/svg/refresh.svg"
											width={12}
											height={12}
											alt="svg"
										></Image>
									</div>
									<div className={styles.space}></div>
								</div>
								<div className={styles.content}>
									<div className={styles.main}>
										<div className={styles.page__wrap}>
											<div className={styles.input} />
											<div className={styles.movie__wrap}>
												<div className={styles.movie} />
												<div className={styles.movie} />
												<div className={styles.movie} />
												<div className={styles.movie} />
												<div className={styles.movie} />
												<div className={styles.movie} />
												<div className={styles.movie} />
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
			<Footer />
		</div>
	);
};

export default Home;
