import type { NextPage } from 'next';

import { useRouter } from 'next/router';

import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import Header from 'components/header/header';

import subscribe from 'pages/subscribe/subscribe.json';

import styles from './accepted.module.scss';

const Accepted: NextPage = () => {
	const router = useRouter();

	return (
		<div className="container">
			<Head>
				<title>Спасибо!</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className="main">
				{subscribe
					.filter((title) => title.id === +router.query.product)
					.map((product) => {
						return (
							<div key={product.id} className={styles.accepted}>
								<div className={styles.circle}>
									<Image
										src="/svg/movies/check.svg"
										width={120}
										height={120}
										alt="svg"
									></Image>
								</div>
								<h1>
									Спасибо <br /> за покупку!
								</h1>
								<p>Товар: подписка на {product.duration} успешно приобретён!</p>
								<Link href="/">
									Вернутсья на главную{' '}
									<Image
										src="/svg/home/link.svg"
										width={16}
										height={16}
										alt="svg"
										draggable={false}
									/>
								</Link>
							</div>
						);
					})}
			</main>
		</div>
	);
};

export default Accepted;
