import type { NextPage } from 'next';

import { useRouter } from 'next/router';
import Head from 'next/head';

import subscribe from 'pages/subscribe/subscribe.json';

import Header from 'components/header/header';
import Footer from 'components/footer/footer';

const Payment: NextPage = () => {
	const router = useRouter();

	return (
		<div className="container">
			<Head>
				<title>Оплата товара</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<main className="main">
				<div>
					{
						subscribe
						.filter((title) => title.id === +router.query.product)
						.map(product => {
							return(
								<div key={product.id}>
									<h1>{product.price}</h1>
								</div>
							)
						})
					}
				</div>
				<Footer />
			</main>
		</div>
	);
};

export default Payment;
